service: updateAddBlock

custom:
  warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: cron(0/5 8-21 ? * MON-SUN *)
      concurrency: 3
      verbose: true
      logRetentionInDays: 3
      folderName: .warmup
      cleanFolder: true
      prewarm: true

provider:
  name: aws
  runtime: python3.11
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "${param:tableArn}"
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "${param:blockTableArn}"

functions:
  updateAddBlock:
    layers:
      - ${param:utilsLayer}
    handler: updateAddBlock.handler
    name: updateAddBlock-${sls:stage}
    memorySize: 128
    timeout: 60
    warmup:
      officeHoursWarmer:
        enabled: true
    events:
      - http:
          path: /updateAddBlock
          method: post
          timeout: 60
          cors: true
          integration: lambda-proxy
          authorizer:
            name: cognitoAuthorizer
            arn: ${param:cognitoArn}
    environment:
      TABLE_NAME: ${param:tableName}
      BLOCK_TABLE_NAME: ${param:blockTableName}

plugins:
  - serverless-plugin-warmup