
service: trackerManagment
app: sweaty-duck-backend

custom:
  warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: cron(0/5 8-21 ? * MON-SUN *)
      concurrency: 3
      verbose: true
      logRetentionInDays: 3
      folderName: .warmup
      cleanFolder: true
      prewarm: true

provider:
  name: aws
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "${param:trackerTableArn}"
          

functions:
  trackerManagment:
    layers: 
      - ${param:fastapiLayer}
      - ${param:magnumLayer}
      - ${param:utilsLayer}
    handler: trackerManagment.handler
    name: trackerManagment-${sls:stage}
    memorySize: 128
    timeout: 60
    warmup:
      officeHoursWarmer:
        enabled: true
    events:
      - http:
          path: /createTrackerTempalte
          method: POST
          timeout: 60
          cors: true
          integration: lambda-proxy
          authorizer:
            name: cognitoAuthorizer
            arn: ${param:cognitoArn}
      - http:
        path: /updateTrackerForUser
        method: POST
        timeout: 60
        cors: true
        integration: lambda-proxy
        authorizer:
          name: cognitoAuthorizer
          arn: ${param:cognitoArn}
      - http:
        path: /`TrackerforUser
        method: GET
        timeout: 60
        cors: true
        integration: lambda-proxy
        authorizer:
          name: cognitoAuthorizer
          arn: ${param:cognitoArn}
    environment:
      TABLE_NAME: ${param:trackerTableArn}
  
plugins:
  - serverless-plugin-warmup