service: getUsers

custom:
  warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: cron(0/5 8-21 ? * MON-SUN *)
      concurrency: 3
      verbose: true
      logRetentionInDays: 3
      folderName: .warmup
      cleanFolder: true
      prewarm: true

provider:
  name: aws
  runtime: python3.11
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "${param:tableArn}"
functions:
  getUsers:
    handler: getUsers.handler
    name: getUsers-${sls:stage}
    memorySize: 128
    timeout: 60
    warmup:
      officeHoursWarmer:
        enabled: true
    events:
      - http:
          path: /users
          method: get
          timeout: 60
          cors: true
          integration: lambda
          authorizer:
            name: cognitoAuthorizer
            arn: ${param:cognitoArn}
            claims:
              - email
              - 'cognito:groups'
    environment:
      TABLE_NAME: ${param:tableName}
plugins:
  - serverless-plugin-warmup