service: getUsers

provider:
  name: aws
  runtime: python3.11
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "${param:tableArn}"
functions:
  getUsers:
    handler: getUsers.handler
    name: getUsers-${sls:stage}
    memorySize: 128
    timeout: 60
    reservedConcurrency: 2
    events:
      - http:
          path: /users
          method: get
          timeout: 60
          cors: true
          integration: lambda
          authorizer:
            name: cognitoAuthorizer
            arn: ${param:cognitoArn}
            claims:
              - email
              - 'cognito:groups'
    environment:
      TABLE_NAME: ${param:tableName}