service: usersRegisteration
app: sweaty-duck-backend

provider:
  name: aws
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "${param:tableArn}"
        - Effect: Allow
          Action:
            - cognito-idp:*
          Resource: "*"
  ecr:
    images:
      userImage:
        path: ./
        platform: linux/amd64
        file: Dockerfile
functions:
  usersRegisteration:
    image: userImage
    timeout: 60
    memorySize: 265
    environment:
      # We are using the output of the shared resources CloudFormation template
      # that is passed down from Serverless Compose, and the staged param "domain".
      TABLE_NAME: ${param:tableName}
      TABLE_ARN: ${param:tableArn}