service: uploadPhoto

provider:
  name: aws
  runtime: python3.11
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "${param:tableArn}"
functions:
  uploadPhoto:
    handler: uploadPhoto.handler
    name: uploadPhoto-${sls:stage}
    memorySize: 128
    timeout: 60
    reservedConcurrency: 2
    events:
      - http:
          path: /uploadPhoto
          method: post
          timeout: 60
          cors: true
          integration: lambda
          authorizer:
            name: cognitoAuthorizer
            arn: ${param:cognitoArn}
            claims:
              - email
              - cognito:username
    environment:
      TABLE_NAME: ${param:tableName}